Replayers > Relayers
bnb-chain/whitepaper pull request #83
Opened 2022-09-26 02:45 UTC by ChanceFCC

Oracle Replayers > Oracle Relayers

2022-11-19 05:10 UTC, Tweakwild113 commented
> Oracle Replayers > Oracle Relayers

So input this

2022-11-19 05:11 UTC, Tweakwild113 commented
Hello

2022-11-19 05:12 UTC, Tweakwild113 approved these changes

2022-11-22 23:22 UTC, Mongkol67 approved these changes

2022-11-22 23:30 UTC, Mongkol67 requested changes

2022-11-22 23:30 UTC, Mongkol67 commented on WHITEPAPER.md
>  The cross-chain fees will be distributed to BC validators together with the normal BC blocking rewards.
#

2022-11-22 23:30 UTC, Mongkol67 commented on WHITEPAPER.md
> -Oracle Replayers should wait for enough blocks to confirm the finality on BSC before submitting and voting for the cross-chain communication packages onto BC.
-

2022-11-23 20:05 UTC, Mongkol67 approved these changes

2022-11-23 20:06 UTC, Mongkol67 approved these changes

2022-11-23 20:07 UTC, Mongkol67 approved these changes

2022-11-24 19:14 UTC, doctorhamed approved these changes

2023-01-13 03:58 UTC, Floyd6531 commented on WHITEPAPER.md
> -Oracle Replayers should wait for enough blocks to confirm the finality on BSC before submitting and voting for the cross-chain communication packages onto BC.
Facts

2023-01-18 04:37 UTC, dammywise12 commented on WHITEPAPER.md
> -Oracle Replayers should wait for enough blocks to confirm the finality on BSC before submitting and voting for the cross-chain communication packages onto BC.
Ok

2023-01-18 04:37 UTC, dammywise12 commented on WHITEPAPER.md
> -Oracle Replayers should wait for enough blocks to confirm the finality on BSC before submitting and voting for the cross-chain communication packages onto BC.
Ok

2023-01-18 21:19 UTC, dammywise12 approved these changes

2023-03-01 16:46 UTC, alice22foster approved these changes

2023-03-01 16:46 UTC, alice22foster commented on WHITEPAPER.md
> -Oracle Replayers should wait for enough blocks to confirm the finality on BSC before submitting and voting for the cross-chain communication packages onto BC.
0xd700a72b077d1bc1d242f3b354dc6d0d9459af7e7e2553d3d8c9d4c0a829509a

2023-11-02 09:49 UTC, closed without merging